// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV9xo0_1qSXBvH3QL1k2JAVkZGm1zwKFU',
    appId: '1:695991344197:web:93b697c34ef0eee86e572c',
    messagingSenderId: '695991344197',
    projectId: 'cau-app-dev',
    authDomain: 'cau-app-dev.firebaseapp.com',
    storageBucket: 'cau-app-dev.appspot.com',
    measurementId: 'G-QC5J068E6J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKfiziq28mPOBZyM8uVf7FMmMATWI_UHM',
    appId: '1:695991344197:android:ce977f70a3d29cf96e572c',
    messagingSenderId: '695991344197',
    projectId: 'cau-app-dev',
    storageBucket: 'cau-app-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXARv4j-e9HD-i2uMolhJaK0ov2qkypTw',
    appId: '1:695991344197:ios:047f95bff614dfb86e572c',
    messagingSenderId: '695991344197',
    projectId: 'cau-app-dev',
    storageBucket: 'cau-app-dev.appspot.com',
    iosBundleId: 'com.example.cauAppDev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXARv4j-e9HD-i2uMolhJaK0ov2qkypTw',
    appId: '1:695991344197:ios:6c58e2071adcfbc86e572c',
    messagingSenderId: '695991344197',
    projectId: 'cau-app-dev',
    storageBucket: 'cau-app-dev.appspot.com',
    iosBundleId: 'com.example.cauAppDev.RunnerTests',
  );
}
